### ISSUE TITLE
Unable to control light full range 0 to 100% on port EXT

### ISSUE THREAD

**Issue by GraceGRD** [weigu1/growing_station#1]
Hey, Great work on making a PWM dimming module for the SpiderFarmer 😊.
I gave it a try and I copied your schematic (optocoupler part) which connects to the spiderfarmer and use an ESP8266 with esphome. 

I notice some weird behavior:
1. DIM button is ON and PWM dimmer connected(@100% duty-cycle), the dim knob becomes an on/off switch and cannot change 
2. Change PWM dimmer to 0% duty-cycle, the dim knob becomes functional again.
3. DIM button is OFF (EXT), PWM dimmer connected (@1 to 100% duty-cycle), the light only dims from 40 to 100% and I'm unable to turn it off.

Did you observer similar behavior?

Tomorrow I'll try attaching a pull-up or pull-down resistor on the output side of the optocoupler, maybe this will resolve my issue.

Just for reference, I added a picture of the hardware PCB and the schematic I drew.
![24-10-21 21-46-28 1174](https://github.com/user-attachments/assets/1efcb48a-89b9-4233-af23-365de483ed18)
![24-10-21 23-35-28 1175](https://github.com/user-attachments/assets/36425048-1a7b-4944-ba77-8c9f15ed8a09)

**Comment by weigu1** [comment]
Hi,

I used it only with the DIM button on external and had no issues with dimming 0-100% and switching it off (value 255).

What about your PWM frequency? Mine was set to 1000Hz.

Regards

**Comment by GraceGRD** [comment]
Resolved the issue... I reversed the collector/emitter on the optocoupler output side 😒. Now I'm able to control it successfully!

**Comment by GraceGRD** [comment]
Closed issue
